"""
Conversation memory for the medical assistant.

Stores the conversation history as a list of (role, message) tuples.
A sliding window keeps only the N most recent exchanges to avoid
overloading the LLM context with long conversations.

An exchange is one user message + one assistant response.
Setting max_exchanges=5 means the last 5 pairs are kept (10 messages total).
"""

from langchain_core.messages import HumanMessage, AIMessage


DEFAULT_MAX_EXCHANGES = 5


class ConversationMemory:
    def __init__(self, max_exchanges: int = DEFAULT_MAX_EXCHANGES):
        """
        Initializes an empty conversation memory.

        Args:
            max_exchanges: Maximum number of user/assistant pairs to retain.
        """
        self.max_exchanges = max_exchanges
        self._history: list[tuple[str, str]] = []

    def _trim_history(self):
        """Keep only the last max_exchanges pairs."""
        max_messages = self.max_exchanges * 2
        if len(self._history) > max_messages:
            self._history = self._history[-max_messages:]

    def add_exchange(self, user_message: str, assistant_message: str):
        """
        Adds a user/assistant exchange to the history.

        Args:
            user_message: The message sent by the user.
            assistant_message: The response generated by the assistant.
        """
        self._history.append(("user", user_message))
        self._history.append(("assistant", assistant_message))
        self._trim_history()

    def add_user_message(self, user_message: str):
        """Adds only a user message to memory."""
        self._history.append(("user", user_message))
        self._trim_history()

    def add_ai_message(self, assistant_message: str):
        """Adds only an assistant message to memory."""
        self._history.append(("assistant", assistant_message))
        self._trim_history()

    def get_langchain_messages(self) -> list:
        """
        Returns the history formatted as LangChain message objects.
        """
        messages = []
        for role, content in self._history:
            if role == "user":
                messages.append(HumanMessage(content=content))
            else:
                messages.append(AIMessage(content=content))
        return messages

    def get_history(self) -> list:
        """
        Alias for compatibility with other parts of the project.
        Returns LangChain-formatted messages.
        """
        return self.get_langchain_messages()

    def clear(self):
        """Clears the entire conversation history."""
        self._history = []
        print("Conversation history cleared.")

    def display(self):
        """Prints the current conversation history in a readable format."""
        if not self._history:
            print("No conversation history yet.")
            return

        print(f"\nConversation history ({len(self._history) // 2} exchange(s)):")
        print("-" * 50)
        for role, content in self._history:
            prefix = "User      " if role == "user" else "Assistant "
            print(f"[{prefix}]: {content}")
        print()

    @property
    def is_empty(self) -> bool:
        """Returns True if no exchanges have been recorded yet."""
        return len(self._history) == 0